### PR TITLE
Sync go.mod into BUILD files

### PR DESCRIPTION
**Pull request by Tatskaari**
This PR makes puku read the go.mod file configured via the please go plugin (config.go.modfile) and write any updates to the third party BUILD file.

### CODE REVIEW

**Review by samwestmoreland — COMMENTED** [review]
Would you mind adding a description 🙏🏽 Which way is the sync going? Is the go.mod the source of truth?

**Comment by Tatskaari** [comment]
> Would you mind adding a description 🙏🏽 Which way is the sync going? Is the go.mod the source of truth?

Sure! Done :)

**Comment by Garbett1** [comment]
Ideally,  I'd split the moving of the `puku` command (with all the other BUILD file changes) into another PR if possible.

**Comment by Garbett1** [comment]
Not sure how we want to handle this, but removal of a dep from `go.mod` isn't reflected in the `BUILD` file.

I did a `go get -u ./...` then ran sync on https://github.com/Garbett1/please-servers/commit/e899d30da35d45f9443b02d16a10c2b79f42b92f

**Comment by Tatskaari** [comment]
> Not sure how we want to handle this, but removal of a dep from `go.mod` isn't reflected in the `BUILD` file.
> 
> I did a `go get -u ./...` then ran sync on [Garbett1/please-servers@e899d30](https://github.com/Garbett1/please-servers/commit/e899d30da35d45f9443b02d16a10c2b79f42b92f)

This is intentional. I want to have a `puku tidy` command one day but it's not trivial.

**Pull request merged**
